// <auto-generated />
using System;
using HomeWard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeWard.Infrastructure.Migrations
{
    [DbContext(typeof(HomeWardDbContext))]
    [Migration("20260617213221_AddJustification")]
    partial class AddJustification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeWard.Domain.Entities.RoleLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionStateLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SessionStates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NotStarted"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Working"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Paused"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finished"
                        });
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromState")
                        .HasColumnType("integer")
                        .HasColumnName("FromStateId");

                    b.Property<int?>("FromStateId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimeElapsed")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToState")
                        .HasColumnType("integer")
                        .HasColumnName("ToStateId");

                    b.Property<int?>("ToStateId")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromStateId");

                    b.HasIndex("ToStateId");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("SessionTransitions", null, t =>
                        {
                            t.Property("FromStateId")
                                .HasColumnName("FromStateId1");

                            t.Property("ToStateId")
                                .HasColumnName("ToStateId1");
                        });
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionTransitionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionTransitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionTransitionId");

                    b.ToTable("SessionTransitionDocuments");
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("RoleId");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", null, t =>
                        {
                            t.Property("RoleId")
                                .HasColumnName("RoleId1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@admin",
                            FirstLastName = "User Admin",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$S7QIDk9XBsePW2GK8qz98.hZIb85Y8lNZCdpoOv8IgtffMfSp4wyG",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.WorkSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BillableTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("PausedTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("RestedTime")
                        .HasColumnType("interval");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("StateId");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("WorkedTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("WorkSessions", null, t =>
                        {
                            t.Property("StateId")
                                .HasColumnName("StateId1");
                        });
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionTransition", b =>
                {
                    b.HasOne("HomeWard.Domain.Entities.SessionStateLookup", null)
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeWard.Domain.Entities.SessionStateLookup", null)
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeWard.Domain.Entities.WorkSession", "WorkSession")
                        .WithMany("History")
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionTransitionDocument", b =>
                {
                    b.HasOne("HomeWard.Domain.Entities.SessionTransition", "SessionTransition")
                        .WithMany("Documents")
                        .HasForeignKey("SessionTransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionTransition");
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.User", b =>
                {
                    b.HasOne("HomeWard.Domain.Entities.RoleLookup", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.WorkSession", b =>
                {
                    b.HasOne("HomeWard.Domain.Entities.SessionStateLookup", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.SessionTransition", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("HomeWard.Domain.Entities.WorkSession", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
